import { Event, User } from './types';

export const MOCK_USERS: User[] = [
  { id: 'u1', name: 'Admin User', email: 'admin@eventhub.pro', role: 'Admin', status: 'Active', joinedAt: '2023-01-01' },
  { id: 'u2', name: 'John Organizer', email: 'organizer@eventhub.pro', role: 'Organizer', status: 'Active', joinedAt: '2023-02-15' },
  { id: 'u3', name: 'Sarah Attendee', email: 'user@eventhub.pro', role: 'User', status: 'Active', joinedAt: '2023-03-10' },
];

export const MOCK_EVENTS: Event[] = [
  {
    id: '1',
    title: 'Global Tech Summit 2024',
    description: 'The premier conference for technology leaders and innovators across the globe.',
    date: '2024-05-15T09:00:00Z',
    location: 'San Francisco, CA',
    category: 'Conference',
    status: 'Published',
    attendees: 450,
    capacity: 500,
    revenue: 125000,
    price: 299,
    organizer_id: 'u2',
    image: 'https://picsum.photos/seed/tech/800/400',
    needs_volunteers: false,
    needs_workers: false
  },
  {
    id: '2',
    title: 'React Advanced Workshop',
    description: 'Deep dive into React 19 features and performance optimization techniques.',
    date: '2024-06-10T10:00:00Z',
    location: 'Remote',
    category: 'Workshop',
    status: 'Published',
    attendees: 85,
    capacity: 100,
    revenue: 8500,
    price: 99,
    organizer_id: 'u2',
    image: 'https://picsum.photos/seed/react/800/400',
    needs_volunteers: false,
    needs_workers: false
  },
  {
    id: '3',
    title: 'Local AI Meetup',
    description: 'Monthly gathering to discuss the latest in LLMs and Generative AI.',
    date: '2024-04-20T18:30:00Z',
    location: 'Austin, TX',
    category: 'Meetup',
    status: 'Published',
    attendees: 120,
    capacity: 150,
    revenue: 0,
    price: 0,
    organizer_id: 'u2',
    image: 'https://picsum.photos/seed/ai/800/400',
    needs_volunteers: true,
    needs_workers: false
  },
  {
    id: '4',
    title: 'Summer Networking Gala',
    description: 'An evening of networking and celebration for industry professionals.',
    date: '2024-07-22T19:00:00Z',
    location: 'New York, NY',
    category: 'Social',
    status: 'Pending',
    attendees: 0,
    capacity: 200,
    revenue: 0,
    price: 49,
    organizer_id: 'u2',
    image: 'https://picsum.photos/seed/party/800/400',
    needs_volunteers: false,
    needs_workers: true
  },
  {
    id: 'fest-1',
    title: 'Ganesha Chaturthi Celebration',
    description: 'Grand celebration of Lord Ganesha with traditional rituals and music.',
    date: '2026-09-14T10:00:00Z',
    location: 'Mumbai, India',
    category: 'Social',
    status: 'Published',
    attendees: 0,
    capacity: 5000,
    revenue: 0,
    price: 0,
    organizer_id: 'u2',
    image: 'https://picsum.photos/seed/ganesha/800/400',
    needs_volunteers: true,
    needs_workers: false
  },
  {
    id: 'fest-2',
    title: 'Krishna Janmashtami',
    description: 'Celebrating the birth of Lord Krishna with Dahi Handi and prayers.',
    date: '2026-09-04T18:00:00Z',
    location: 'Mathura, India',
    category: 'Social',
    status: 'Published',
    attendees: 0,
    capacity: 3000,
    revenue: 0,
    price: 0,
    organizer_id: 'u2',
    image: 'https://picsum.photos/seed/krishna/800/400',
    needs_volunteers: true,
    needs_workers: true
  },
  {
    id: 'fest-3',
    title: 'Holi Festival of Colors',
    description: 'Celebrate the arrival of spring with colors, music, and sweets.',
    date: '2026-03-03T10:00:00Z',
    location: 'Delhi, India',
    category: 'Social',
    status: 'Published',
    attendees: 0,
    capacity: 10000,
    revenue: 0,
    price: 0,
    organizer_id: 'u2',
    image: 'https://picsum.photos/seed/holi2/800/400',
    needs_volunteers: true,
    needs_workers: false
  },
  {
    id: 'fest-4',
    title: 'International Yoga Day',
    description: 'Join thousands in a mass yoga session for health and peace.',
    date: '2026-06-21T06:00:00Z',
    location: 'Rishikesh, India',
    category: 'Social',
    status: 'Published',
    attendees: 0,
    capacity: 2000,
    revenue: 0,
    price: 0,
    organizer_id: 'u2',
    image: 'https://picsum.photos/seed/yoga/800/400',
    needs_volunteers: false,
    needs_workers: false
  },
  {
    id: 'fest-5',
    title: 'Navratri Dandiya Night',
    description: 'Traditional folk dance celebration with vibrant costumes and music.',
    date: '2026-10-10T19:00:00Z',
    location: 'Surat, India',
    category: 'Social',
    status: 'Published',
    attendees: 0,
    capacity: 8000,
    revenue: 0,
    price: 300,
    organizer_id: 'u2',
    image: 'https://picsum.photos/seed/dandiya/800/400',
    needs_volunteers: true,
    needs_workers: true
  },
  {
    id: 'fest-6',
    title: 'Diwali Grand Mela',
    description: 'A huge fair with shopping, food stalls, and fireworks display.',
    date: '2026-11-08T17:00:00Z',
    location: 'Lucknow, India',
    category: 'Social',
    status: 'Published',
    attendees: 0,
    capacity: 15000,
    revenue: 0,
    price: 0,
    organizer_id: 'u2',
    image: 'https://picsum.photos/seed/diwali2/800/400',
    needs_volunteers: true,
    needs_workers: false
  },
  {
    id: 'fest-7',
    title: 'Christmas Carnival',
    description: 'Winter wonderland with rides, games, and festive treats.',
    date: '2026-12-25T11:00:00Z',
    location: 'Kolkata, India',
    category: 'Social',
    status: 'Published',
    attendees: 0,
    capacity: 5000,
    revenue: 0,
    price: 100,
    organizer_id: 'u2',
    image: 'https://picsum.photos/seed/christmas/800/400',
    needs_volunteers: false,
    needs_workers: true
  },
  {
    id: 'coll-1',
    title: 'PCACS Education Fair 2026',
    description: 'Annual education fair for career guidance and university admissions.',
    date: '2026-03-15T10:00:00Z',
    location: 'Panvel Campus, PCACS',
    category: 'Conference',
    status: 'Published',
    attendees: 0,
    capacity: 1000,
    revenue: 0,
    price: 0,
    organizer_id: 'u2',
    image: 'https://picsum.photos/seed/edu/800/400',
    needs_volunteers: true,
    needs_workers: false
  },
  {
    id: 'coll-2',
    title: 'Mega Blood Donation Camp',
    description: 'NSS organized blood donation drive to save lives.',
    date: '2026-05-10T09:00:00Z',
    location: 'PCACS Auditorium',
    category: 'Social',
    status: 'Published',
    attendees: 0,
    capacity: 500,
    revenue: 0,
    price: 0,
    organizer_id: 'u2',
    image: 'https://picsum.photos/seed/blood/800/400',
    needs_volunteers: true,
    needs_workers: false
  },
  {
    id: 'coll-3',
    title: 'Career Counseling Seminar',
    description: 'Expert sessions on career paths and skill development.',
    date: '2026-04-12T11:00:00Z',
    location: 'PCACS Seminar Hall',
    category: 'Workshop',
    status: 'Published',
    attendees: 0,
    capacity: 300,
    revenue: 0,
    price: 0,
    organizer_id: 'u2',
    image: 'https://picsum.photos/seed/career/800/400',
    needs_volunteers: false,
    needs_workers: false
  },
  {
    id: 'coll-4',
    title: 'Azadi Ka Amrit Mahotsav',
    description: 'Celebrating 79 years of Indian Independence with cultural programs.',
    date: '2026-08-15T08:00:00Z',
    location: 'PCACS Ground',
    category: 'Social',
    status: 'Published',
    attendees: 0,
    capacity: 2000,
    revenue: 0,
    price: 0,
    organizer_id: 'u2',
    image: 'https://picsum.photos/seed/azadi/800/400',
    needs_volunteers: true,
    needs_workers: false
  },
  {
    id: 'coll-5',
    title: 'Free Eye Check-up Camp',
    description: 'Community service event for health awareness and eye care.',
    date: '2026-06-20T10:00:00Z',
    location: 'PCACS Health Center',
    category: 'Social',
    status: 'Published',
    attendees: 0,
    capacity: 200,
    revenue: 0,
    price: 0,
    organizer_id: 'u2',
    image: 'https://picsum.photos/seed/eye/800/400',
    needs_volunteers: true,
    needs_workers: true
  }
];
